# lychee link checker configuration

# Check links in markdown files.
include = [ ".*\\.md$" ]

# Cache results to avoid re-checking known links too often.
cache = true

# Don't fail on mailto links, localhost, shields, or commit permalinks.
exclude = [
  "^http://127.0.0.1",
  "^http://localhost",
  "^https://github.com/sguzman/",
  "^https://img.shields.io/",
  "^mailto:",
]

# Ignore a specific markdown file by path
exclude_path = [
  "docs/migration/.*-DeepWiki.md",
  "examples/",
  "new-project/",
  "tests/",
]
